// Copyright (c) 2026 H0llyW00dzZ All rights reserved.
//
// By accessing or using this software, you agree to be bound by the terms
// of the License Agreement, which you can find at LICENSE files.

// @generated by protoc-gen-es v2.11.0
// @generated from file helloworld/v1/helloworld.proto (package helloworld.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file helloworld/v1/helloworld.proto.
 */
export declare const file_helloworld_v1_helloworld: GenFile;

/**
 * SayHelloRequest is the request message for the SayHello RPC.
 *
 * @generated from message helloworld.v1.SayHelloRequest
 */
export declare type SayHelloRequest = Message<"helloworld.v1.SayHelloRequest"> & {
  /**
   * name is the name to greet.
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message helloworld.v1.SayHelloRequest.
 * Use `create(SayHelloRequestSchema)` to create a new message.
 */
export declare const SayHelloRequestSchema: GenMessage<SayHelloRequest>;

/**
 * SayHelloResponse is the response message for the SayHello RPC.
 *
 * @generated from message helloworld.v1.SayHelloResponse
 */
export declare type SayHelloResponse = Message<"helloworld.v1.SayHelloResponse"> & {
  /**
   * message is the greeting text.
   *
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message helloworld.v1.SayHelloResponse.
 * Use `create(SayHelloResponseSchema)` to create a new message.
 */
export declare const SayHelloResponseSchema: GenMessage<SayHelloResponse>;

/**
 * SayHelloServerStreamRequest is the request message for the SayHelloServerStream RPC.
 *
 * @generated from message helloworld.v1.SayHelloServerStreamRequest
 */
export declare type SayHelloServerStreamRequest = Message<"helloworld.v1.SayHelloServerStreamRequest"> & {
  /**
   * name is the name to greet.
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message helloworld.v1.SayHelloServerStreamRequest.
 * Use `create(SayHelloServerStreamRequestSchema)` to create a new message.
 */
export declare const SayHelloServerStreamRequestSchema: GenMessage<SayHelloServerStreamRequest>;

/**
 * SayHelloServerStreamResponse is the response message for the SayHelloServerStream RPC.
 *
 * @generated from message helloworld.v1.SayHelloServerStreamResponse
 */
export declare type SayHelloServerStreamResponse = Message<"helloworld.v1.SayHelloServerStreamResponse"> & {
  /**
   * message is the greeting text.
   *
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message helloworld.v1.SayHelloServerStreamResponse.
 * Use `create(SayHelloServerStreamResponseSchema)` to create a new message.
 */
export declare const SayHelloServerStreamResponseSchema: GenMessage<SayHelloServerStreamResponse>;

/**
 * GreeterService is a sample gRPC service demonstrating unary and server-streaming RPCs.
 *
 * @generated from service helloworld.v1.GreeterService
 */
export declare const GreeterService: GenService<{
  /**
   * SayHello sends a single greeting (unary RPC).
   *
   * @generated from rpc helloworld.v1.GreeterService.SayHello
   */
  sayHello: {
    methodKind: "unary";
    input: typeof SayHelloRequestSchema;
    output: typeof SayHelloResponseSchema;
  },
  /**
   * SayHelloServerStream sends multiple greetings over a server stream.
   *
   * @generated from rpc helloworld.v1.GreeterService.SayHelloServerStream
   */
  sayHelloServerStream: {
    methodKind: "server_streaming";
    input: typeof SayHelloServerStreamRequestSchema;
    output: typeof SayHelloServerStreamResponseSchema;
  },
}>;

