// Copyright (c) 2026 H0llyW00dzZ All rights reserved.
//
// By accessing or using this software, you agree to be bound by the terms
// of the License Agreement, which you can find at LICENSE files.

// @generated by protoc-gen-es v2.11.0
// @generated from file helloworld/v1/helloworld.proto (package helloworld.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file helloworld/v1/helloworld.proto.
 */
export const file_helloworld_v1_helloworld = /*@__PURE__*/
  fileDesc("Ch5oZWxsb3dvcmxkL3YxL2hlbGxvd29ybGQucHJvdG8SDWhlbGxvd29ybGQudjEiHwoPU2F5SGVsbG9SZXF1ZXN0EgwKBG5hbWUYASABKAkiIwoQU2F5SGVsbG9SZXNwb25zZRIPCgdtZXNzYWdlGAEgASgJIisKG1NheUhlbGxvU2VydmVyU3RyZWFtUmVxdWVzdBIMCgRuYW1lGAEgASgJIi8KHFNheUhlbGxvU2VydmVyU3RyZWFtUmVzcG9uc2USDwoHbWVzc2FnZRgBIAEoCTLUAQoOR3JlZXRlclNlcnZpY2USTQoIU2F5SGVsbG8SHi5oZWxsb3dvcmxkLnYxLlNheUhlbGxvUmVxdWVzdBofLmhlbGxvd29ybGQudjEuU2F5SGVsbG9SZXNwb25zZSIAEnMKFFNheUhlbGxvU2VydmVyU3RyZWFtEiouaGVsbG93b3JsZC52MS5TYXlIZWxsb1NlcnZlclN0cmVhbVJlcXVlc3QaKy5oZWxsb3dvcmxkLnYxLlNheUhlbGxvU2VydmVyU3RyZWFtUmVzcG9uc2UiADABQsIBChFjb20uaGVsbG93b3JsZC52MUIPSGVsbG93b3JsZFByb3RvUAFaR2dpdGh1Yi5jb20vSDBsbHlXMDBkelovZ3JwYy10ZW1wbGF0ZS9wa2cvZ2VuL2hlbGxvd29ybGQvdjE7aGVsbG93b3JsZHYxogIDSFhYqgINSGVsbG93b3JsZC5WMcoCDUhlbGxvd29ybGRcVjHiAhlIZWxsb3dvcmxkXFYxXEdQQk1ldGFkYXRh6gIOSGVsbG93b3JsZDo6VjFiBnByb3RvMw");

/**
 * Describes the message helloworld.v1.SayHelloRequest.
 * Use `create(SayHelloRequestSchema)` to create a new message.
 */
export const SayHelloRequestSchema = /*@__PURE__*/
  messageDesc(file_helloworld_v1_helloworld, 0);

/**
 * Describes the message helloworld.v1.SayHelloResponse.
 * Use `create(SayHelloResponseSchema)` to create a new message.
 */
export const SayHelloResponseSchema = /*@__PURE__*/
  messageDesc(file_helloworld_v1_helloworld, 1);

/**
 * Describes the message helloworld.v1.SayHelloServerStreamRequest.
 * Use `create(SayHelloServerStreamRequestSchema)` to create a new message.
 */
export const SayHelloServerStreamRequestSchema = /*@__PURE__*/
  messageDesc(file_helloworld_v1_helloworld, 2);

/**
 * Describes the message helloworld.v1.SayHelloServerStreamResponse.
 * Use `create(SayHelloServerStreamResponseSchema)` to create a new message.
 */
export const SayHelloServerStreamResponseSchema = /*@__PURE__*/
  messageDesc(file_helloworld_v1_helloworld, 3);

/**
 * GreeterService is a sample gRPC service demonstrating unary and server-streaming RPCs.
 *
 * @generated from service helloworld.v1.GreeterService
 */
export const GreeterService = /*@__PURE__*/
  serviceDesc(file_helloworld_v1_helloworld, 0);

