// Copyright (c) 2026 H0llyW00dzZ All rights reserved.
//
// By accessing or using this software, you agree to be bound by the terms
// of the License Agreement, which you can find at LICENSE files.

// @generated by protoc-gen-connect-es v1.6.1
// @generated from file helloworld/v1/helloworld.proto (package helloworld.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SayHelloRequest, SayHelloResponse, SayHelloServerStreamRequest, SayHelloServerStreamResponse } from "./helloworld_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * GreeterService is a sample gRPC service demonstrating unary and server-streaming RPCs.
 *
 * @generated from service helloworld.v1.GreeterService
 */
export const GreeterService = {
  typeName: "helloworld.v1.GreeterService",
  methods: {
    /**
     * SayHello sends a single greeting (unary RPC).
     *
     * @generated from rpc helloworld.v1.GreeterService.SayHello
     */
    sayHello: {
      name: "SayHello",
      I: SayHelloRequest,
      O: SayHelloResponse,
      kind: MethodKind.Unary,
    },
    /**
     * SayHelloServerStream sends multiple greetings over a server stream.
     *
     * @generated from rpc helloworld.v1.GreeterService.SayHelloServerStream
     */
    sayHelloServerStream: {
      name: "SayHelloServerStream",
      I: SayHelloServerStreamRequest,
      O: SayHelloServerStreamResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
};

