<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helloworld/v1/helloworld.proto

namespace Helloworld\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * SayHelloResponse is the response message for the SayHello RPC.
 *
 * Generated from protobuf message <code>helloworld.v1.SayHelloResponse</code>
 */
class SayHelloResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * message is the greeting text.
     *
     * Generated from protobuf field <code>string message = 1 [json_name = "message"];</code>
     */
    protected $message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $message
     *           message is the greeting text.
     * }
     */
    public function __construct($data = NULL) {
        \Helloworld\V1\GPBMetadata\Helloworld::initOnce();
        parent::__construct($data);
    }

    /**
     * message is the greeting text.
     *
     * Generated from protobuf field <code>string message = 1 [json_name = "message"];</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * message is the greeting text.
     *
     * Generated from protobuf field <code>string message = 1 [json_name = "message"];</code>
     * @param string $var
     * @return $this
     */
    public function setMessage(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->message = $var;

        return $this;
    }

}

