<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helloworld/v1/helloworld.proto

namespace Helloworld\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * SayHelloServerStreamRequest is the request message for the SayHelloServerStream RPC.
 *
 * Generated from protobuf message <code>helloworld.v1.SayHelloServerStreamRequest</code>
 */
class SayHelloServerStreamRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * name is the name to greet.
     *
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     */
    protected $name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           name is the name to greet.
     * }
     */
    public function __construct($data = NULL) {
        \Helloworld\V1\GPBMetadata\Helloworld::initOnce();
        parent::__construct($data);
    }

    /**
     * name is the name to greet.
     *
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * name is the name to greet.
     *
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

}

