// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: helloworld/v1/helloworld.proto

#include "helloworld/v1/helloworld.pb.h"
#include "helloworld/v1/helloworld.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace helloworld {
namespace v1 {

static const char* GreeterService_method_names[] = {
  "/helloworld.v1.GreeterService/SayHello",
  "/helloworld.v1.GreeterService/SayHelloServerStream",
};

std::unique_ptr< GreeterService::Stub> GreeterService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GreeterService::Stub> stub(new GreeterService::Stub(channel, options));
  return stub;
}

GreeterService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SayHello_(GreeterService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SayHelloServerStream_(GreeterService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status GreeterService::Stub::SayHello(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloRequest& request, ::helloworld::v1::SayHelloResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::helloworld::v1::SayHelloRequest, ::helloworld::v1::SayHelloResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SayHello_, context, request, response);
}

void GreeterService::Stub::async::SayHello(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloRequest* request, ::helloworld::v1::SayHelloResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::helloworld::v1::SayHelloRequest, ::helloworld::v1::SayHelloResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

void GreeterService::Stub::async::SayHello(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloRequest* request, ::helloworld::v1::SayHelloResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::helloworld::v1::SayHelloResponse>* GreeterService::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::helloworld::v1::SayHelloResponse, ::helloworld::v1::SayHelloRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SayHello_, context, request);
}

::grpc::ClientAsyncResponseReader< ::helloworld::v1::SayHelloResponse>* GreeterService::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSayHelloRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::helloworld::v1::SayHelloServerStreamResponse>* GreeterService::Stub::SayHelloServerStreamRaw(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloServerStreamRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::helloworld::v1::SayHelloServerStreamResponse>::Create(channel_.get(), rpcmethod_SayHelloServerStream_, context, request);
}

void GreeterService::Stub::async::SayHelloServerStream(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloServerStreamRequest* request, ::grpc::ClientReadReactor< ::helloworld::v1::SayHelloServerStreamResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::helloworld::v1::SayHelloServerStreamResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_SayHelloServerStream_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::helloworld::v1::SayHelloServerStreamResponse>* GreeterService::Stub::AsyncSayHelloServerStreamRaw(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloServerStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::helloworld::v1::SayHelloServerStreamResponse>::Create(channel_.get(), cq, rpcmethod_SayHelloServerStream_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::helloworld::v1::SayHelloServerStreamResponse>* GreeterService::Stub::PrepareAsyncSayHelloServerStreamRaw(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloServerStreamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::helloworld::v1::SayHelloServerStreamResponse>::Create(channel_.get(), cq, rpcmethod_SayHelloServerStream_, context, request, false, nullptr);
}

GreeterService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GreeterService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GreeterService::Service, ::helloworld::v1::SayHelloRequest, ::helloworld::v1::SayHelloResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GreeterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::helloworld::v1::SayHelloRequest* req,
             ::helloworld::v1::SayHelloResponse* resp) {
               return service->SayHello(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GreeterService_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< GreeterService::Service, ::helloworld::v1::SayHelloServerStreamRequest, ::helloworld::v1::SayHelloServerStreamResponse>(
          [](GreeterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::helloworld::v1::SayHelloServerStreamRequest* req,
             ::grpc::ServerWriter<::helloworld::v1::SayHelloServerStreamResponse>* writer) {
               return service->SayHelloServerStream(ctx, req, writer);
             }, this)));
}

GreeterService::Service::~Service() {
}

::grpc::Status GreeterService::Service::SayHello(::grpc::ServerContext* context, const ::helloworld::v1::SayHelloRequest* request, ::helloworld::v1::SayHelloResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GreeterService::Service::SayHelloServerStream(::grpc::ServerContext* context, const ::helloworld::v1::SayHelloServerStreamRequest* request, ::grpc::ServerWriter< ::helloworld::v1::SayHelloServerStreamResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace helloworld
}  // namespace v1
#include <grpcpp/ports_undef.inc>

