// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: helloworld/v1/helloworld.proto
// Original file comments:
// Copyright (c) 2026 H0llyW00dzZ All rights reserved.
//
// By accessing or using this software, you agree to be bound by the terms
// of the License Agreement, which you can find at LICENSE files.
//
#ifndef GRPC_helloworld_2fv1_2fhelloworld_2eproto__INCLUDED
#define GRPC_helloworld_2fv1_2fhelloworld_2eproto__INCLUDED

#include "helloworld/v1/helloworld.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace helloworld {
namespace v1 {

// GreeterService is a sample gRPC service demonstrating unary and server-streaming RPCs.
class GreeterService final {
 public:
  static constexpr char const* service_full_name() {
    return "helloworld.v1.GreeterService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // SayHello sends a single greeting (unary RPC).
    virtual ::grpc::Status SayHello(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloRequest& request, ::helloworld::v1::SayHelloResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::v1::SayHelloResponse>> AsyncSayHello(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::v1::SayHelloResponse>>(AsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::v1::SayHelloResponse>> PrepareAsyncSayHello(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::v1::SayHelloResponse>>(PrepareAsyncSayHelloRaw(context, request, cq));
    }
    // SayHelloServerStream sends multiple greetings over a server stream.
    std::unique_ptr< ::grpc::ClientReaderInterface< ::helloworld::v1::SayHelloServerStreamResponse>> SayHelloServerStream(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloServerStreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::helloworld::v1::SayHelloServerStreamResponse>>(SayHelloServerStreamRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::helloworld::v1::SayHelloServerStreamResponse>> AsyncSayHelloServerStream(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloServerStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::helloworld::v1::SayHelloServerStreamResponse>>(AsyncSayHelloServerStreamRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::helloworld::v1::SayHelloServerStreamResponse>> PrepareAsyncSayHelloServerStream(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloServerStreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::helloworld::v1::SayHelloServerStreamResponse>>(PrepareAsyncSayHelloServerStreamRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // SayHello sends a single greeting (unary RPC).
      virtual void SayHello(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloRequest* request, ::helloworld::v1::SayHelloResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SayHello(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloRequest* request, ::helloworld::v1::SayHelloResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // SayHelloServerStream sends multiple greetings over a server stream.
      virtual void SayHelloServerStream(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloServerStreamRequest* request, ::grpc::ClientReadReactor< ::helloworld::v1::SayHelloServerStreamResponse>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::v1::SayHelloResponse>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::v1::SayHelloResponse>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::helloworld::v1::SayHelloServerStreamResponse>* SayHelloServerStreamRaw(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloServerStreamRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::helloworld::v1::SayHelloServerStreamResponse>* AsyncSayHelloServerStreamRaw(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloServerStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::helloworld::v1::SayHelloServerStreamResponse>* PrepareAsyncSayHelloServerStreamRaw(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloServerStreamRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SayHello(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloRequest& request, ::helloworld::v1::SayHelloResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::v1::SayHelloResponse>> AsyncSayHello(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::v1::SayHelloResponse>>(AsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::v1::SayHelloResponse>> PrepareAsyncSayHello(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::v1::SayHelloResponse>>(PrepareAsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::helloworld::v1::SayHelloServerStreamResponse>> SayHelloServerStream(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloServerStreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::helloworld::v1::SayHelloServerStreamResponse>>(SayHelloServerStreamRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::helloworld::v1::SayHelloServerStreamResponse>> AsyncSayHelloServerStream(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloServerStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::helloworld::v1::SayHelloServerStreamResponse>>(AsyncSayHelloServerStreamRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::helloworld::v1::SayHelloServerStreamResponse>> PrepareAsyncSayHelloServerStream(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloServerStreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::helloworld::v1::SayHelloServerStreamResponse>>(PrepareAsyncSayHelloServerStreamRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SayHello(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloRequest* request, ::helloworld::v1::SayHelloResponse* response, std::function<void(::grpc::Status)>) override;
      void SayHello(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloRequest* request, ::helloworld::v1::SayHelloResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SayHelloServerStream(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloServerStreamRequest* request, ::grpc::ClientReadReactor< ::helloworld::v1::SayHelloServerStreamResponse>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::helloworld::v1::SayHelloResponse>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::helloworld::v1::SayHelloResponse>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::helloworld::v1::SayHelloServerStreamResponse>* SayHelloServerStreamRaw(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloServerStreamRequest& request) override;
    ::grpc::ClientAsyncReader< ::helloworld::v1::SayHelloServerStreamResponse>* AsyncSayHelloServerStreamRaw(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloServerStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::helloworld::v1::SayHelloServerStreamResponse>* PrepareAsyncSayHelloServerStreamRaw(::grpc::ClientContext* context, const ::helloworld::v1::SayHelloServerStreamRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SayHello_;
    const ::grpc::internal::RpcMethod rpcmethod_SayHelloServerStream_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // SayHello sends a single greeting (unary RPC).
    virtual ::grpc::Status SayHello(::grpc::ServerContext* context, const ::helloworld::v1::SayHelloRequest* request, ::helloworld::v1::SayHelloResponse* response);
    // SayHelloServerStream sends multiple greetings over a server stream.
    virtual ::grpc::Status SayHelloServerStream(::grpc::ServerContext* context, const ::helloworld::v1::SayHelloServerStreamRequest* request, ::grpc::ServerWriter< ::helloworld::v1::SayHelloServerStreamResponse>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SayHello() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::helloworld::v1::SayHelloRequest* /*request*/, ::helloworld::v1::SayHelloResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::helloworld::v1::SayHelloRequest* request, ::grpc::ServerAsyncResponseWriter< ::helloworld::v1::SayHelloResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SayHelloServerStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SayHelloServerStream() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SayHelloServerStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHelloServerStream(::grpc::ServerContext* /*context*/, const ::helloworld::v1::SayHelloServerStreamRequest* /*request*/, ::grpc::ServerWriter< ::helloworld::v1::SayHelloServerStreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHelloServerStream(::grpc::ServerContext* context, ::helloworld::v1::SayHelloServerStreamRequest* request, ::grpc::ServerAsyncWriter< ::helloworld::v1::SayHelloServerStreamResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SayHello<WithAsyncMethod_SayHelloServerStream<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SayHello() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::helloworld::v1::SayHelloRequest, ::helloworld::v1::SayHelloResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::helloworld::v1::SayHelloRequest* request, ::helloworld::v1::SayHelloResponse* response) { return this->SayHello(context, request, response); }));}
    void SetMessageAllocatorFor_SayHello(
        ::grpc::MessageAllocator< ::helloworld::v1::SayHelloRequest, ::helloworld::v1::SayHelloResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::helloworld::v1::SayHelloRequest, ::helloworld::v1::SayHelloResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::helloworld::v1::SayHelloRequest* /*request*/, ::helloworld::v1::SayHelloResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SayHello(
      ::grpc::CallbackServerContext* /*context*/, const ::helloworld::v1::SayHelloRequest* /*request*/, ::helloworld::v1::SayHelloResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SayHelloServerStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SayHelloServerStream() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::helloworld::v1::SayHelloServerStreamRequest, ::helloworld::v1::SayHelloServerStreamResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::helloworld::v1::SayHelloServerStreamRequest* request) { return this->SayHelloServerStream(context, request); }));
    }
    ~WithCallbackMethod_SayHelloServerStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHelloServerStream(::grpc::ServerContext* /*context*/, const ::helloworld::v1::SayHelloServerStreamRequest* /*request*/, ::grpc::ServerWriter< ::helloworld::v1::SayHelloServerStreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::helloworld::v1::SayHelloServerStreamResponse>* SayHelloServerStream(
      ::grpc::CallbackServerContext* /*context*/, const ::helloworld::v1::SayHelloServerStreamRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SayHello<WithCallbackMethod_SayHelloServerStream<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SayHello() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::helloworld::v1::SayHelloRequest* /*request*/, ::helloworld::v1::SayHelloResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SayHelloServerStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SayHelloServerStream() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SayHelloServerStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHelloServerStream(::grpc::ServerContext* /*context*/, const ::helloworld::v1::SayHelloServerStreamRequest* /*request*/, ::grpc::ServerWriter< ::helloworld::v1::SayHelloServerStreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SayHello() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::helloworld::v1::SayHelloRequest* /*request*/, ::helloworld::v1::SayHelloResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SayHelloServerStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SayHelloServerStream() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SayHelloServerStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHelloServerStream(::grpc::ServerContext* /*context*/, const ::helloworld::v1::SayHelloServerStreamRequest* /*request*/, ::grpc::ServerWriter< ::helloworld::v1::SayHelloServerStreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHelloServerStream(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SayHello() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SayHello(context, request, response); }));
    }
    ~WithRawCallbackMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::helloworld::v1::SayHelloRequest* /*request*/, ::helloworld::v1::SayHelloResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SayHello(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SayHelloServerStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SayHelloServerStream() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->SayHelloServerStream(context, request); }));
    }
    ~WithRawCallbackMethod_SayHelloServerStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHelloServerStream(::grpc::ServerContext* /*context*/, const ::helloworld::v1::SayHelloServerStreamRequest* /*request*/, ::grpc::ServerWriter< ::helloworld::v1::SayHelloServerStreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* SayHelloServerStream(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SayHello() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::helloworld::v1::SayHelloRequest, ::helloworld::v1::SayHelloResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::helloworld::v1::SayHelloRequest, ::helloworld::v1::SayHelloResponse>* streamer) {
                       return this->StreamedSayHello(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::helloworld::v1::SayHelloRequest* /*request*/, ::helloworld::v1::SayHelloResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSayHello(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::helloworld::v1::SayHelloRequest,::helloworld::v1::SayHelloResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SayHello<Service > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_SayHelloServerStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_SayHelloServerStream() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::helloworld::v1::SayHelloServerStreamRequest, ::helloworld::v1::SayHelloServerStreamResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::helloworld::v1::SayHelloServerStreamRequest, ::helloworld::v1::SayHelloServerStreamResponse>* streamer) {
                       return this->StreamedSayHelloServerStream(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_SayHelloServerStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SayHelloServerStream(::grpc::ServerContext* /*context*/, const ::helloworld::v1::SayHelloServerStreamRequest* /*request*/, ::grpc::ServerWriter< ::helloworld::v1::SayHelloServerStreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedSayHelloServerStream(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::helloworld::v1::SayHelloServerStreamRequest,::helloworld::v1::SayHelloServerStreamResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_SayHelloServerStream<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_SayHello<WithSplitStreamingMethod_SayHelloServerStream<Service > > StreamedService;
};

}  // namespace v1
}  // namespace helloworld


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_helloworld_2fv1_2fhelloworld_2eproto__INCLUDED
