<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helloworld/v1/helloworld.proto

namespace Helloworld\V1\GPBMetadata;

class Helloworld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x95\x05\x0A\x1Ehelloworld/v1/helloworld.proto\x12\x0Dhelloworld.v1\"%\x0A\x0FSayHelloRequest\x12\x12\x0A\x04name\x18\x01 \x01(\x09R\x04name\",\x0A\x10SayHelloResponse\x12\x18\x0A\x07message\x18\x01 \x01(\x09R\x07message\"1\x0A\x1BSayHelloServerStreamRequest\x12\x12\x0A\x04name\x18\x01 \x01(\x09R\x04name\"8\x0A\x1CSayHelloServerStreamResponse\x12\x18\x0A\x07message\x18\x01 \x01(\x09R\x07message2\xD4\x01\x0A\x0EGreeterService\x12M\x0A\x08SayHello\x12\x1E.helloworld.v1.SayHelloRequest\x1A\x1F.helloworld.v1.SayHelloResponse\"\x00\x12s\x0A\x14SayHelloServerStream\x12*.helloworld.v1.SayHelloServerStreamRequest\x1A+.helloworld.v1.SayHelloServerStreamResponse\"\x000\x01B\xC2\x01\x0A\x11com.helloworld.v1B\x0FHelloworldProtoP\x01ZGgithub.com/H0llyW00dzZ/grpc-template/pkg/gen/helloworld/v1;helloworldv1\xA2\x02\x03HXX\xAA\x02\x0DHelloworld.V1\xCA\x02\x0DHelloworld\\V1\xE2\x02\x19Helloworld\\V1\\GPBMetadata\xEA\x02\x0EHelloworld::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

